spring.application.name=backoffice-java-project

# Konfigurasi Database (JPA + Hibernate)
spring.datasource.url=jdbc:oracle:thin:@146.190.149.240:1521:xe
spring.datasource.username=backoffice
spring.datasource.password=bni1234/
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=admin
# spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.default_schema=BACKOFFICE
spring.jpa.properties.hibernate.format_sql=true

# Port server Spring Boot
server.port=8181

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.out-of-order=false
spring.flyway.ignore-missing-migrations=false
spring.flyway.validate-on-migrate=true
spring.flyway.clean-on-validation-error=false
spring.flyway.clean-disabled=false
spring.flyway.schemas=BACKOFFICE
spring.flyway.table=flyway_schema_history_palembang
spring.flyway.oracle.sqlplus=true
