-- Buat sequence untuk ID pada MASTER_USER_COBA
CREATE SEQUENCE "BACKOFFICE"."MASTER_USER_COBA_SEQ" START WITH 1 INCREMENT BY 1;

-- Buat tabel MASTER_USER_COBA
CREATE TABLE "BACKOFFICE"."MASTER_USER_COBA"(
    ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(255) NOT NULL
);

-- Buat sequence untuk ID pada MASTER_ACCOUNT_COBA
CREATE SEQUENCE "BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ" START WITH 1 INCREMENT BY 1;

-- Buat tabel MASTER_ACCOUNT_COBA
CREATE TABLE "BACKOFFICE"."MASTER_ACCOUNT_COBA" (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    BALANCE NUMBER(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_MASTER_ACCOUNT_USER FOREIGN KEY (USER_ID)
        REFERENCES "BACKOFFICE"."MASTER_USER_COBA"(ID) ON DELETE CASCADE
);

