-- Insert untuk MASTER_USER_COBA
INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Elora');

INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Fuad');

INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Iyan');

INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Umam');

INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Mail');

INSERT INTO "BACKOFFICE"."MASTER_USER_COBA" (ID, FULL_NAME)
VALUES ("BACKOFFICE"."MASTER_USER_COBA_SEQ".NEXTVAL, 'Andi');


-- Insert untuk MASTER_ACCOUNT_COBA
INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Elora'), 1500000.00);

INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Fuad'), 2000000.00);

INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Iyan'), 1200000.00);
INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Iyan'), 800000.00);

INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Umam'), 900000.00);

INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Mail'), 2500000.00);
INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Mail'), 750000.00);

INSERT INTO "BACKOFFICE"."MASTER_ACCOUNT_COBA" (ID, USER_ID, BALANCE)
VALUES ("BACKOFFICE"."MASTER_ACCOUNT_COBA_SEQ".NEXTVAL, (SELECT ID FROM "BACKOFFICE"."MASTER_USER_COBA" WHERE FULL_NAME = 'Andi'), 10000000.00);
