-- Buat sequence untuk ID pada MASTER_USER_COBA
CREATE SEQUENCE "BACKOFFICE"."MASTER_PRODUCT_COBA_SEQ" START
WITH
    1 INCREMENT BY 1;

CREATE TABLE "BACKOFFICE"."MASTER_PRODUCT_COBA" (
        ID NUMBER PRIMARY KEY,
        PRODUCT_NAME VARCHAR(255) NOT NULL,
        ACCOUNT_STATUS VARCHAR(255) NOT NULL
    );

