INSERT INTO "BACKOFFICE"."MASTER_PRODUCT_COBA" (ID,PRODUCT_NAME, ACCOUNT_STATUS)
VALUES ("BACKOFFICE"."MASTER_PRODUCT_COBA_SEQ".NEXTVAL, 'Tabunganku', 'Active');


INSERT INTO "BACKOFFICE"."MASTER_PRODUCT_COBA" (ID,PRODUCT_NAME, ACCOUNT_STATUS)
VALUES ("BACKOFFICE"."MASTER_PRODUCT_COBA_SEQ".NEXTVAL, 'Taplus Muda', 'Inactive');


INSERT INTO "BACKOFFICE"."MASTER_PRODUCT_COBA" (ID,PRODUCT_NAME, ACCOUNT_STATUS)
VALUES ("BACKOFFICE"."MASTER_PRODUCT_COBA_SEQ".NEXTVAL, 'Deposito', 'Active');


INSERT INTO "BACKOFFICE"."MASTER_PRODUCT_COBA" (ID,PRODUCT_NAME, ACCOUNT_STATUS)
VALUES ("BACKOFFICE"."MASTER_PRODUCT_COBA_SEQ".NEXTVAL, 'Taplus Pegawai', 'Active');

ALTER TABLE "BACKOFFICE"."MASTER_ACCOUNT_COBA" DROP COLUMN "ACCOUNT_TYPE";

